### PR TITLE
Deleting broken Azure Pipeline Deploy

### PR DESCRIPTION
**Pull request by v-fearam**
The tactical decision was to delete and keep updated only manual deploy.
The second part is create a task to redo a pipeline deploy from scratch when we decide it is appropriated. (ADO 419822)

### CODE REVIEW

**Comment by ckittel** [comment]
As mentioned in AzDO, what do we need to do with https://docs.microsoft.com/azure/architecture/microservices/ci-cd-kubernetes if this content gets deleted here?

**Comment by doodlemania2** [comment]
Just redirect to the baseline?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ckittel** [comment]
@doodlemania2 -- can you say more about your suggestion to redirect the CI CD Kubernetes document to the Baseline?  The Baseline doesn't contain CI/CD content.  This article will need some writer's time to align with the proposed changes of DELETING this component of the reference implementation.  A decision on this will block forward progress on the workitem.

**Comment by doodlemania2** [comment]
It was just a thought that it might be easiest to redirect people to the baseline if what we have isn't working/is removed. Understood that there's not CI/CD in the baseline, just that sending them to the baseline is better than 404ing when / if we don't have cycles correct the material itself.

**Comment by ckittel** [comment]
Oh, it's good content, just need the writer to remove the references to the reference implementation and backfill any details from the RI into the RA/Article that will be lost because of that.

**Comment by neilpeterson** [comment]
@ckittel I believe I've all-ready removed reference to the RI from the content as well given it a light scrub. Is there something specific remaining that needs updating?

**Comment by ckittel** [comment]
All good, thanks!  @v-fearam and I missed that task in the sprint. Unblocked now.  Sorry for the dustup.

**Comment by magrande** [comment]
Closing the PR as this is being addressed in another PR.

**Pull request closed without merging**
